// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231124124943_mg1")]
    partial class mg1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Kafka",
                            CratedAt = new DateTime(2023, 11, 24, 15, 49, 43, 828, DateTimeKind.Local).AddTicks(1303),
                            Name = "Donusum",
                            UpdatedAt = new DateTime(2023, 11, 24, 15, 49, 43, 828, DateTimeKind.Local).AddTicks(1326)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mario Puzo",
                            CratedAt = new DateTime(2023, 11, 24, 15, 49, 43, 828, DateTimeKind.Local).AddTicks(1350),
                            Name = "The Godfather",
                            UpdatedAt = new DateTime(2023, 11, 24, 15, 49, 43, 828, DateTimeKind.Local).AddTicks(1352)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Aldous Huxley",
                            CratedAt = new DateTime(2023, 11, 24, 15, 49, 43, 828, DateTimeKind.Local).AddTicks(1355),
                            Name = "Cesur Yeni Dunya",
                            UpdatedAt = new DateTime(2023, 11, 24, 15, 49, 43, 828, DateTimeKind.Local).AddTicks(1356)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
